services:
  webapi:
    build:
      context: .
      dockerfile: src/HealthApp.Api/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    container_name: healthapp-api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__MongoDb=mongodb://root:root@mongo:27017/HealthAppDb?authSource=admin
    depends_on:
      - mongo
    networks:
      - healthapp-network
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s

  mongo:
    image: mongo:latest
    container_name: healthapp-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - healthapp-network

volumes:
  mongo-data:

networks:
  healthapp-network: